# Generated by Django 4.1 on 2022-09-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberstatus',
            options={'verbose_name': 'Member Status', 'verbose_name_plural': 'Member Status'},
        ),
    ]
