# Generated by Django 4.1 on 2022-09-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_soaps_assessment_bpjs'),
        ('data_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BPJSCode',
            new_name='BPJSCodes',
        ),
    ]
