# Generated by Django 4.1 on 2022-09-08 04:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date Time')),
                ('patient', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_appointment', to='patient.patients')),
            ],
            options={
                'db_table': 'next_appointment',
            },
        ),
    ]
