# Generated by Django 4.1 on 2022-09-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Number'),
        ),
    ]
