# Generated by Django 4.1 on 2022-09-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soaps',
            name='number',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Number'),
        ),
    ]
