# Generated by Django 4.1 on 2022-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soaps',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
