# Generated by Django 4.1 on 2022-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_soaps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soaps',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='soap/images'),
        ),
    ]
