# Generated by Django 4.1 on 2022-09-05 07:17

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_teethlowerleft_eight_alter_teethlowerleft_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soaps',
            name='patient',
            field=modelcluster.fields.ParentalKey(limit_choices_to=patient.models.Soaps.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='related_patient', to='patient.patients'),
        ),
        migrations.DeleteModel(
            name='MedicalImage',
        ),
    ]
