# Generated by Django 4.1 on 2022-09-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_soaps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='is_bpjs',
            field=models.BooleanField(default=False, verbose_name='BPJS'),
        ),
    ]
