# Generated by Django 4.1 on 2022-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patients_name_alter_patients_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soaps',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='ID'),
        ),
    ]
