# Generated by Django 4.1 on 2022-09-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_support', '0001_initial'),
        ('patient', '0004_patients_is_bpjs'),
    ]

    operations = [
        migrations.AddField(
            model_name='soaps',
            name='assessment_bpjs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_support.bpjscode', verbose_name='Assessment BPJS'),
        ),
    ]
