# Generated by Django 4.1 on 2022-09-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_soaps_assessment_bpjs'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='bjps_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BPJS Number'),
        ),
        migrations.AddField(
            model_name='patients',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIK'),
        ),
    ]
