# Generated by Django 4.1 on 2022-09-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patients_bjps_number_patients_nik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='bjps_number',
            new_name='bpjs_number',
        ),
    ]
