# Generated by Django 4.1 on 2022-09-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_rename_bjps_number_patients_bpjs_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='bpjs_number',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='is_bpjs',
        ),
        migrations.RemoveField(
            model_name='soaps',
            name='assessment_bpjs',
        ),
    ]
