# Generated by Django 4.1 on 2022-09-21 00:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_patients_bpjs_number_remove_patients_is_bpjs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('allergies', models.CharField(max_length=100, verbose_name='Allergies')),
                ('patient', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_allergies', to='patient.patients')),
            ],
            options={
                'verbose_name': 'allergy',
                'verbose_name_plural': 'allergies',
                'db_table': 'allergies',
            },
        ),
    ]
