# Generated by Django 4.1 on 2022-09-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'doctor', 'verbose_name_plural': 'doctors'},
        ),
    ]
