# Generated by Django 4.1 on 2022-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='is_cancel',
            field=models.BooleanField(default=False, verbose_name='Cancel Invoice'),
        ),
    ]
