# Generated by Django 4.1 on 2022-09-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Check and Correct'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Angka'),
        ),
    ]
