# Generated by Django 4.1 on 2022-09-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoices_is_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='is_cancel',
            field=models.BooleanField(default=False, verbose_name='Cancel'),
        ),
    ]
