# Generated by Django 4.1 on 2022-09-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoices_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='total',
        ),
    ]
