# Generated by Django 4.1 on 2022-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoices_is_final_alter_invoices_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Number'),
        ),
    ]
