# Generated by Django 4.1 on 2022-09-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoices_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoices',
            options={'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
    ]
